project: 
  type: website
  output-dir: docs
  title: "CSU ESS 330 Lab 6/8"

website:
  title: "CSU ESS 330 Lab 6/8"
  navbar:
    left:
      - href: index.qmd
        text: Lab-6
      - href: hyperparameter-tuning.qmd
        text: Lab-8
        
format:
  html:
    self-contained: true